import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <div className="flex h-screen overflow-x-hidden bg-gray-default ">
            <Sidebar>
              <main className="px-6 mx-auto overflow-y-auto max-w-screen">
                {children}
              </main>
            </Sidebar>
          </div>
        </div>
      </body>
    </html>
  );
}
